module.exports = [
    { title: 'Apply for Aadhar Card', category: 'Personal Document', link: 'https://uidai.gov.in/my-aadhaar.html' },
    { title: 'Link Aadhar to Bank Account', category: 'Personal Document', link: 'https://www.rbi.org.in/Scripts/BS_Social-2.aspx' },
    { title: 'Download Aadhar Card', category: 'Personal Document', link: 'https://eaadhaar.uidai.gov.in/' },
    { title: 'Apply for PAN Card', category: 'Personal Document', link: 'https://www.incometaxindia.gov.in/pages/tax-services/apply-for-pan.aspx' },
    { title: 'Apply for Voter ID', category: 'Personal Document', link: 'https://www.nvsp.in/' },
    { title: 'Renew Passport', category: 'Personal Document', link: 'https://portal2.passportindia.gov.in/AppOnlineProject/welcomeLink' },
    { title: 'Check EPF Balance', category: 'Money & banking', link: 'https://www.epfindia.gov.in/site_en/index.php' },
    { title: 'Link PAN with Aadhar', category: 'Money & banking', link: 'https://incometaxindiaefiling.gov.in/e-Filing/Services/LinkAadhaarHome.html' },
    { title: 'Banking Services Registration', category: 'Money & banking', link: 'https://www.rbi.org.in/Scripts/BS_Social-2.aspx' },
    { title: 'GST Registration', category: 'Money & banking', link: 'https://www.gst.gov.in/' },
    { title: 'Apply for Land Record', category: 'Land & Property', link: 'https://www.landrecords.com/' },
    { title: 'Apply for Property Registration', category: 'Land & Property', link: 'https://www.registration.tn.gov.in/' },
    { title: 'Get Domicile Certificate', category: 'Land & Property', link: 'https://www.india.gov.in/portal/domicile-certificate' },
    { title: 'Apply for Ration Card', category: 'Goverment Scheme & Welface', link: 'https://nfsa.gov.in' },
    { title: 'Check PM Kisan Status', category: 'Goverment Scheme & Welface', link: 'https://pmkisan.gov.in/' },
    { title: 'Apply for PMAY Scheme', category: 'Goverment Scheme & Welface', link: 'https://pmaymis.gov.in/' },
    { title: 'Apply for Sukanya Samriddhi Yojana', category: 'Goverment Scheme & Welface', link: 'https://www.sbi.co.in/web/personal-banking/investments-deposits/sukanya-samriddhi-account' },
    { title: 'Apply for Jan Dhan Yojana', category: 'Goverment Scheme & Welface', link: 'https://pmjdy.gov.in/' },
    { title: 'Apply for Ayushman Bharat', category: 'Goverment Scheme & Welface', link: 'https://pmjay.gov.in/' },
    { title: 'Apply for PMGDISHA', category: 'Goverment Scheme & Welface', link: 'https://www.pmgdisha.in/' },
    { title: 'Apply for National Scholarship', category: 'Education & student services', link: 'https://scholarships.gov.in/' },
    { title: 'Apply for JEE Exam', category: 'Education & student services', link: 'https://jeemain.nta.nic.in/' },
    { title: 'Apply for NEET Exam', category: 'Education & student services', link: 'https://neet.nta.nic.in/' },
    { title: 'Apply for GATE Exam', category: 'Education & student services', link: 'https://gate.iitk.ac.in/' },
    { title: 'Apply for UPSC Civil Services Exam', category: 'Employment & skill develpment', link: 'https://www.upsc.gov.in/examinations' },
    { title: 'Apply for SSC CGL Exam', category: 'Employment & skill develpment', link: 'https://ssc.nic.in' },
    { title: 'Apply for IBPS PO Exam', category: 'Employment & skill develpment', link: 'https://www.ibps.in' },
    { title: 'Check CBSE Results', category: 'Education & student services', link: 'https://cbseresults.nic.in/' },
    { title: 'Apply for Indian Army Recruitment', category: 'Employment & skill develpment', link: 'https://joinindianarmy.nic.in' },
    { title: 'Apply for Indian Navy Recruitment', category: 'Employment & skill develpment', link: 'https://www.joinindiannavy.gov.in' },
    { title: 'Apply for Indian Airforce Recruitment', category: 'Employment & skill develpment', link: 'https://indianairforce.nic.in' },
    { title: 'Apply for Police Recruitment', category: 'Police & Legal', link: 'https://www.police.gov.in' },
    { title: 'Apply for Passport Verification', category: 'Police & Legal', link: 'https://passportindia.gov.in' },
    { title: 'Apply for FIR Online', category: 'Police & Legal', link: 'https://www.e-fir.gov.in' },
    { title: 'Apply for Legal Aid', category: 'Police & Legal', link: 'https://legalaidindia.gov.in/' },
    { title: 'Track Legal Case Status', category: 'Police & Legal', link: 'https://ecourts.gov.in' },
    { title: 'Apply for Traffic Challan Payment', category: 'Police & Legal', link: 'https://echallan.parivahan.gov.in' },
    { title: 'Pay Utility Bills Online', category: 'Bill & utilities', link: 'https://www.bharatbillpay.com/' },
    { title: 'Check Electricity Bill', category: 'Bill & utilities', link: 'https://www.tangedco.gov.in' },
    { title: 'Pay Water Bill', category: 'Bill & utilities', link: 'https://www.tnurbn.org' },
    { title: 'Apply for Vehicle Registration', category: 'Vehicle & Transport', link: 'https://vahan.nic.in/vahanservice/vahan/ui/statevalidation/HomeForm' },
    { title: 'Check Vehicle Insurance', category: 'Vehicle & Transport', link: 'https://www.irda.gov.in' },
    { title: 'Apply for Driving License', category: 'Vehicle & Transport', link: 'https://sarathi.parivahan.gov.in' },
    { title: 'Apply for Vehicle Pollution Certificate', category: 'Vehicle & Transport', link: 'https://parivahan.gov.in' },
    { title: 'Check Vehicle Tax Payment Status', category: 'Vehicle & Transport', link: 'https://vahan.parivahan.gov.in' },
    { title: 'Apply for NOC for Vehicle', category: 'Vehicle & Transport', link: 'https://www.parivahan.gov.in' },
    { title: 'Apply for H1B Visa', category: 'Employment & skill develpment', link: 'https://www.uscis.gov/h1b' },
    { title: 'Apply for B1/B2 Visa', category: 'Employment & skill develpment', link: 'https://travel.state.gov/content/travel/en/us-visas.html' },
    { title: 'Apply for OCI Card', category: 'Personal Document', link: 'https://ociservices.gov.in' },
    { title: 'Check Aadhar Card Status', category: 'Personal Document', link: 'https://www.uidai.gov.in/check-aadhaar-status' },
    { title: 'Apply for PNB Digital Banking', category: 'Money & banking', link: 'https://www.pnbindia.in' },
    { title: 'Apply for TN Ration Card', category: 'Goverment Scheme & Welface', link: 'https://www.tnpds.gov.in' },
    { title: 'Check TN Ration Card Status', category: 'Goverment Scheme & Welface', link: 'https://www.tnpds.gov.in/epds/epds' },
    { title: 'Apply for TN Marriage Certificate', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/marriagecertificate' },
    { title: 'Apply for Birth Certificate in TN', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/birthcertificate' },
    { title: 'Apply for Death Certificate in TN', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/deathcertificate' },
    { title: 'Apply for Caste Certificate in TN', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/castecertificate' },
    { title: 'Apply for Income Certificate in TN', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/incomecertificate' },
    { title: 'Apply for Domicile Certificate in TN', category: 'Personal Document', link: 'https://www.tn.gov.in/knowtamilnadu/domicilecertificate' },
    { title: 'Apply for TN Voter ID', category: 'Personal Document', link: 'https://www.nvsp.in' },
    { title: 'Apply for TN Passport', category: 'Personal Document', link: 'https://www.passportindia.gov.in' },
    { title: 'Apply for TN Land Record', category: 'Land & Property', link: 'https://eservices.tn.gov.in/landrecords' },
    { title: 'Apply for TN Property Registration', category: 'Land & Property', link: 'https://www.tnreginet.gov.in/portal' },
    { title: 'Check TN Land Record', category: 'Land & Property', link: 'https://www.tnreginet.gov.in/portal' },
    { title: 'Apply for Patta Copy in TN', category: 'Land & Property', link: 'https://www.tn.gov.in/knowtamilnadu/pattacopy' },
    { title: 'Apply for TN EC (Encumbrance Certificate)', category: 'Land & Property', link: 'https://www.tnreginet.gov.in/portal' },
    { title: 'Apply for TN Property Mutation', category: 'Land & Property', link: 'https://www.tnreginet.gov.in/portal' },
    { title: 'Check TN Vehicle Registration Status', category: 'Vehicle & Transport', link: 'https://www.tn.gov.in/knowtamilnadu/vehicle-registration' },
    { title: 'Apply for TN Driving License', category: 'Vehicle & Transport', link: 'https://www.tnsta.gov.in' },
    { title: 'Check TN Driving License Status', category: 'Vehicle & Transport', link: 'https://www.tnsta.gov.in' },
    { title: 'Apply for TN Vehicle Pollution Certificate', category: 'Vehicle & Transport', link: 'https://www.parivahan.gov.in' },
    { title: 'Apply for TN Vehicle Tax Payment', category: 'Vehicle & Transport', link: 'https://www.tn.gov.in/knowtamilnadu/vehicle-tax' },
    { title: 'Apply for TN Transport Online Services', category: 'Vehicle & Transport', link: 'https://www.tnsta.gov.in' },
    { title: 'Apply for TN Police Clearance Certificate', category: 'Police & Legal', link: 'https://www.tnpolice.gov.in' },
    { title: 'Apply for TN FIR Online', category: 'Police & Legal', link: 'https://www.tnpolice.gov.in' },
    { title: 'Check TN FIR Status', category: 'Police & Legal', link: 'https://www.tnpolice.gov.in' },
    { title: 'Apply for TN Legal Aid', category: 'Police & Legal', link: 'https://www.tn.gov.in/knowtamilnadu/legal-aid' },
    { title: 'Apply for TN Traffic Challan', category: 'Police & Legal', link: 'https://www.tnpolice.gov.in' },
    { title: 'Apply for TN Aadhar Update', category: 'Personal Document', link: 'https://uidai.gov.in' },
    { title: 'Apply for TN Electricity Bill Payment', category: 'Bill & utilities', link: 'https://www.tangedco.gov.in' },
    { title: 'Apply for TN Water Bill Payment', category: 'Bill & utilities', link: 'https://www.tnurbn.org' },
    { title: 'Apply for TN Gas Bill Payment', category: 'Bill & utilities', link: 'https://www.indianpetro.com' },
    { title: 'Apply for TN Property Tax Payment', category: 'Bill & utilities', link: 'https://www.tn.gov.in/knowtamilnadu/propertytax' },
    { title: 'Apply for TN Health Insurance Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/healthinsurance' },
    { title: 'Apply for TN Widow Pension', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/widow-pension' },
    { title: 'Apply for TN Old Age Pension', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/old-age-pension' },
    { title: 'Apply for TN Differently Abled Pension', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/differently-abled-pension' },
    { title: 'Apply for TN Farmer’s Welfare Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/farmers-welfare' },
    { title: 'Apply for TN Chief Minister’s Relief Fund', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/cm-relief-fund' },
    { title: 'Apply for TN CMGA (Chief Minister’s Green Agriculture) Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/cmga-scheme' },
    { title: 'Apply for TN Solar Subsidy Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/solar-subsidy' },
    { title: 'Apply for TN Building Plan Approval', category: 'Land & Property', link: 'https://www.tn.gov.in/knowtamilnadu/building-plan' },
    { title: 'Check TN Building Plan Status', category: 'Land & Property', link: 'https://www.tn.gov.in/knowtamilnadu/building-plan-status' },
    { title: 'Apply for TN Water Connection', category: 'Bill & utilities', link: 'https://www.tnurbn.org' },
    { title: 'Check TN Election Results', category: 'Education & student services', link: 'https://www.tn.gov.in' },
    { title: 'Apply for TN Employment Exchange Registration', category: 'Employment & skill develpment', link: 'https://www.tn.gov.in/knowtamilnadu/employment-exchange' },
    { title: 'Apply for TN Apprenticeship Scheme', category: 'Employment & skill develpment', link: 'https://www.apprenticeship.gov.in' },
    { title: 'Apply for TN Labour Welfare Fund', category: 'Employment & skill develpment', link: 'https://www.tn.gov.in/knowtamilnadu/labour-welfare-fund' },
    { title: 'Apply for TN Skill Development Program', category: 'Employment & skill develpment', link: 'https://www.skilldevelopment.tn.gov.in' },
    { title: 'Check TN Educational Scholarship Status', category: 'Education & student services', link: 'https://www.tn.gov.in/knowtamilnadu/scholarship-status' },
    { title: 'Apply for TN Government College Admission', category: 'Education & student services', link: 'https://www.tngovtcolleges.com' },
    { title: 'Apply for TN Government School Admission', category: 'Education & student services', link: 'https://www.tn.gov.in/knowtamilnadu/govt-school-admission' },
    { title: 'Apply for TN CM Fellowship Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/cm-fellowship' },
    { title: 'Apply for TN Youth Empowerment Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/youth-empowerment' },
    { title: 'Apply for TN Free Coaching Scheme', category: 'Education & student services', link: 'https://www.tn.gov.in/knowtamilnadu/free-coaching' },
    { title: 'Apply for TN Digital Literacy Program', category: 'Employment & skill develpment', link: 'https://www.tn.gov.in/knowtamilnadu/digital-literacy' },
    { title: 'Apply for TN Job Mela Registration', category: 'Employment & skill develpment', link: 'https://www.tn.gov.in/knowtamilnadu/job-mela' },
    { title: 'Apply for TN Livelihood Support Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/livelihood-support' },
    { title: 'Apply for TN Subsidy for Dairy Farming', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/dairy-subsidy' },
    { title: 'Apply for TN Horticulture Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/horticulture-scheme' },
    { title: 'Apply for TN Rural Development Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/rural-development' },
    { title: 'Check TN Board Exam Results', category: 'Education & student services', link: 'https://tnresults.nic.in' },
    { title: 'Apply for TN Technical Education Courses', category: 'Education & student services', link: 'https://www.tndte.gov.in' },
    { title: 'Apply for TN Medical Admission', category: 'Education & student services', link: 'https://www.tnhealth.org' },
    { title: 'Check TN CET Results', category: 'Education & student services', link: 'https://www.annauniv.edu' },
    { title: 'Apply for TN Rural Housing Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/rural-housing' },
    { title: 'Apply for TN Women Welfare Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/women-welfare' },
    { title: 'Apply for TN Chief Minister’s Special Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/cm-special-scheme' },
    { title: 'Apply for TN Emergency Relief Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/emergency-relief' },
    { title: 'Check TN RTO Updates', category: 'Vehicle & Transport', link: 'https://www.tnsta.gov.in' },
    { title: 'Apply for TN Bus Pass', category: 'Vehicle & Transport', link: 'https://www.tnstc.in' },
    { title: 'Apply for TN Self-Employment Scheme', category: 'Goverment Scheme & Welface', link: 'https://www.tn.gov.in/knowtamilnadu/self-employment' },
    { title: "TNPSC Group 1 Exam",category: "Education & student services", link: "https://www.tnpsc.gov.in/notification.html"},
    { title: "TANCET 2025 Registration",category: "Education & student services",link: "https://www.annauniv.edu/tancet2025"},
    { title: "TN 12th Result Portal",category: "Education & student services",link: "https://www.dge.tn.gov.in"},
    { title: "Tamil Nadu Open University Admission",category: "Education & student services",link: "https://www.tnou.ac.in"},
    { title: "TNSCERT Textbook Download",category: "Education & student services",link: "https://www.tnschools.gov.in"},
    { title: "Tamil Nadu School Education Recruitment",category: "Education & student services",link: "https://www.tnpsc.gov.in"},
    { title: "Tamil Nadu State Scholarship Portal",category: "Education & student services",link: "https://www.tnscholarship.org"},
    { title: "National Eligibility Test (NET) Tamil Nadu",category: "Education & student services",link: "https://www.natboard.edu.in"},
    { title: "TNEA 2025 Application",category: "Education & student services",link: "https://www.tneaonline.org"},
    { title: "Scholarships for Tamil Nadu Students",category: "Education & student services",link: "https://www.tnscholarships.in"},
    { title: "TN Government Education Loan",category: "Education & student services",link: "https://www.tn.gov.in/scholarship"},
    { title: "Tamil Nadu Teachers Recruitment Board",category: "Education & student services",link: "https://www.trb.tn.nic.in"},
    { title: "TN Higher Education Commission",category: "Education & student services",link: "https://www.tnhedc.gov.in"},
    { title: "Tamil Nadu Student Health Scheme",category: "Education & student services",link: "https://www.tnhealth.org"},
    { title: "Tamil Nadu Rural Education Fund",category: "Education & student services",link: "https://www.ruraleducation.tn.gov.in"},
    { title: "Tamil Nadu State Council for Higher Education",category: "Education & student services",link: "https://www.tnscer.org"},
    { title: "Tamil Nadu University Admissions",category: "Education & student services",link: "https://www.annauniv.edu"},
    { title: "TNPSC Group 2 Exam",category: "Education & student services",link: "https://www.tnpsc.gov.in/notification.html"},
    { title: "Kongu Arts & Science College Admissions",category: "Education & student services",link: "https://www.kongu.edu"},
    { title: "Tamil Nadu Medical Colleges List",category: "Education & student services",link: "https://www.tnhealth.org"},
    { title: "TN School Scholarship Scheme",category: "Education & student services",link: "https://www.scholarships.tn.gov.in"},
    { title: "Tamil Nadu Engineering Admissions (TNEA) 2025",category: "Education & student services",link: "https://www.tneaonline.org"}    
];


